version: '3.8'

services:
  db:
    image: 'postgres:16-alpine'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    restart: always
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=service_receipt
      - POSTGRES_PASSWORD=/run/secrets/db-password
      - POSTGRES_USER=user_db
    healthcheck:
      test: [ "CMD",  "pg_isready -d service_receipt -U user_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    container_name: 'redis-server'
    restart: unless-stopped
    ports:
      - "6378:6379"
  wkhtmltopdf:
    build:
      context: .
volumes:
  postgres_data:
secrets:
  db-password:
    file: app_receipt/db/password.txt

