## Create image based on the official openjdk 8-jre-alpine image from the dockerhub
#FROM openjdk:8-jre-alpine
#
## Install wkhtmltopdf
#RUN apk add --no-cache wkhtmltopdf
#
#ENTRYPOINT ["wkhtmltopdf"]
#
#
#
##FROM debian:buster
##
##RUN apt-get update \
##    && apt-get install -y \
##        curl \
##        libxrender1 \
##        libjpeg62-turbo \
##        fontconfig \
##        libxtst6 \
##        xfonts-75dpi \
##        xfonts-base \
##        xz-utils
##
##RUN curl "https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_amd64.deb" -L -o "wkhtmltopdf.deb"
##RUN dpkg -i wkhtmltopdf.deb
##
##ENTRYPOINT ["wkhtmltopdf"]