# Generated by Django 5.0.6 on 2024-06-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_receipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATE', 'in the creation queue'), ('READY', 'ready to print'), ('RELEASE', 'release')], default='CREATE', max_length=7),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
