# Generated by Django 5.0.6 on 2024-06-19 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_receipt', '0002_order_status_delete_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='order',
            name='printer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_receipt.printer'),
            preserve_default=False,
        ),
    ]
