# Generated by Django 5.0.6 on 2024-06-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_receipt', '0003_remove_order_restaurant_order_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='print_queue',
            field=models.IntegerField(default=0),
        ),
    ]
