# Generated by Django 5.0.6 on 2024-07-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_receipt', '0004_printer_print_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='print_queue',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
