# Generated by Django 5.0.6 on 2024-07-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_receipt', '0005_alter_printer_print_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READY', 'Ready'), ('RELEASE', 'Release')], default='CREATE', max_length=7),
        ),
    ]
